remote_theme: pages-themes/slate@v0.2.0
title: BeanRunner
# description: A workflow automation platform for Spring Boot
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one